### ISSUE TITLE
About Minigames

### ISSUE THREAD

**Issue by Anderson-SG** [DocTi/albion-network#15]
I forked the project but in fact if possible I would like to be a contributor.

I’m mapping all the events related to fishing, the only thing I haven’t yet managed to detect is the position of the minigame float,

Is there a way to detect the position of the buoy in the fishing minigame via packages?

![image](https://user-images.githubusercontent.com/37317374/88348857-e3a54f80-cd24-11ea-95a0-2e213b1bca48.png)

**Comment by Anderson-SG** [comment]
@DocTi

**Comment by DocTi** [comment]
@Anderson-SG, hello!
I also tried to find similar information in network messages, but with no result. Even before the Albion Network project, a bot was developed based on the EMGUCV library. There is an algorithm for a mini-game, I can try to search for the source code of this project.

**Comment by Anderson-SG** [comment]
After testing a little I understood how it works, when you receive the "started minigame" package We received some numbers inside them that we should use to calculate how to solve the minigame, Some information is:

`{[0, 521299]}
{[1, 6]}
{[2, 637311457067367456]}
{[3, 2]}
{[4, 1]}
{[5, 4]}
{[6, 0.3]}
{[7, 1.1]}
{[8, 4.5]}
{[9, -1]}
{[10, 1]}
{[11, 6]}
{[12, 2.5]}
{[13, 10]}
{[15, 7]}
{[252, 330]}`

Speed ​​of the buoy, Strength of resistance of the fish, level of the fish, id of the player who is fishing this are some of them, I noticed the change in this information to each different fish hooked, keeping the pattern when one fish is the same as another.

I already have a library that solves the minigame using opencv, however it is in python and I would like to have everything unified in one place, if you still have this code I am willing to share it would be incredible.

**Comment by DocTi** [comment]
@Anderson-SG Hi! Take the time. Please write to me in Discord DocTi#1410.
