### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by KauzDs** [DocTi/albion-network#16]
When I try to install the package using NuGet console I get this error:

Attempting to gather dependency information for package 'Albion.Network.4.5.0' with respect to project 'AlbionRadaro', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 338 ms
Attempting to resolve dependencies for package 'Albion.Network.4.5.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Albion.Network.4.5.0'
Resolved actions to install package 'Albion.Network.4.5.0'
Retrieving package 'Albion.Network 4.5.0' from 'nuget.org'.
Retrieving package 'PhotonPackageParser 4.0.0' from 'nuget.org'.
Install failed. Rolling back...
Package 'PhotonPackageParser.4.0.0 : PcapDotNet [0.10.2, )' does not exist in project 'AlbionRadaro'
Package 'PhotonPackageParser.4.0.0 : PcapDotNet [0.10.2, )' does not exist in folder 'F:\Test\AO-Radar\packages'
Executing nuget actions took 984 ms
Install-Package : Could not install package 'PhotonPackageParser 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does 
not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Albion.Network
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by DocTi** [comment]
NETFramework, Version=v4.5 not supported

**Comment by KauzDs** [comment]
How do I change to a supported version?
