### ISSUE TITLE
I often have the problem that the .dll crashes.

### ISSUE THREAD

**Issue by Triky313** [DocTi/albion-network#17]
I often have the problem that the .dll crashes:
System.ArgumentException: Type code: 83 not implemented???

- ERROR 2021-02-11 18:00:22 - [38] message:StartDeviceCapture 
 method:PacketHandler 
 stacktrace:SharpPcap.LibPcap.Windows.pcap_dispatch > SharpPcap.LibPcap.PcapDevice.PacketHandler > SharpPcap.Npcap.NpcapDevice.SendPacketArrivalEvent > SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent > StatisticsAnalysisTool.Network.NetworkController.PacketHandler 
 line: 121 
System.ArgumentException: Type code: 83 not implemented.
   bei Protocol16.Protocol16Deserializer.Deserialize(Protocol16Stream input, Byte typeCode)
   bei Protocol16.Protocol16Deserializer.DeserializeParameterTable(Protocol16Stream input)
   bei Protocol16.Protocol16Deserializer.DeserializeEventData(Protocol16Stream input)
   bei PhotonPackageParser.PhotonParser.HandleSendReliable(Byte[] source, Int32& offset, Int32& commandLength)
   bei PhotonPackageParser.PhotonParser.HandleFinishedSegmentedPackage(Byte[] totalPayload)
   bei PhotonPackageParser.PhotonParser.HandleSegmentedPayload(Int32 startSequenceNumber, Int32 totalLength, Int32 fragmentLength, Int32 fragmentOffset, Byte[] source, Int32& offset)
   bei PhotonPackageParser.PhotonParser.HandleSendFragment(Byte[] source, Int32& offset, Int32& commandLength)
   bei PhotonPackageParser.PhotonParser.HandleCommand(Byte[] source, Int32& offset)
   bei PhotonPackageParser.PhotonParser.ReceivePacket(Byte[] payload)
   bei Albion.Network.AlbionParser.Albion.Network.IPhotonReceiver.ReceivePacket(Byte[] payload)
   bei StatisticsAnalysisTool.Network.NetworkController.PacketHandler(Object sender, CaptureEventArgs e) in ..\StatisticsAnalysisTool\Network\NetworkController.cs:Zeile 116.
The thread 0x63dc has exited with code 0 (0x0).
'StatisticsAnalysisTool.exe' (CLR v4.0.30319: StatisticsAnalysisTool.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase.resources\v4.0_4.0.0.0_de_31bf3856ad364e35\WindowsBase.resources.dll'. Module was built without symbols.
An unhandled exception of type 'System.ArgumentException' occurred in WindowsBase.dll

**Comment by DocTi** [comment]
The error occurs on the side https://github.com/0blu/PhotonPackageParser. Solve this problem in your project with try/catch. This error occurs because the event is using a custom data model. The parser does not support custom data models.
