### ISSUE TITLE
As of the upcoming "Lands Awakened" update, there is a problem with the ReceivePacket class

### ISSUE THREAD

**Issue by Triky313** [DocTi/albion-network#18]
As of the upcoming "Lands Awakened" update, there is a problem with the ReceivePacket class

**Exception**:
System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'

You can already see this on the test server.

Can we resolve the error promptly? Can I help you somehow?

**Comment by DocTi** [comment]
https://github.com/DocTi/albion-network/releases/tag/5.0.1
